# Generated by Django 2.2.10 on 2020-03-22 12:57

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookingstatus',
            options={'base_manager_name': '_plain_manager'},
        ),
        migrations.AlterModelManagers(
            name='bookingstatus',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_plain_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='booking.BookingStatus', verbose_name='Booking status'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='gender',
            field=models.CharField(blank=True, choices=[('mrs', 'Mrs'), ('mr', 'Mr')], max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='notes',
            field=models.TextField(blank=True, max_length=1024, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='time_unit',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Time unit'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='title',
            field=models.CharField(blank=True, choices=[('dr', 'Dr.'), ('prof', 'Prof.')], max_length=10, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='bookingstatustranslation',
            name='master',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='booking.BookingStatus'),
        ),
    ]
