# Generated by Django 2.2.10 on 2020-03-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation',
            name='address',
            field=models.CharField(default='kajaanintie 46', max_length=20),
        ),
        migrations.AddField(
            model_name='activation',
            name='isDogwalker',
            field=models.BooleanField(default=True),
        ),
    ]
